services:
  postgres:
    image: postgres:18
    container_name: kineo-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  mysql:
    image: mysql:8.4
    container_name: kineo-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: RootPassword123!
      MYSQL_DATABASE: kineo_test
      MYSQL_USER: kineo_user
      MYSQL_PASSWORD: kineo_password
    ports:
      - "3306:3306"
    command:
      - --mysql-native-password=ON
    volumes:
      - mysql_data:/var/lib/mysql

  mssql:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: kineo-mssql
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "MyVeryStrongPassword2025!"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  postgres_data:
  mysql_data:
  mssql_data:
